/// Flutter icons MyFlutterApp
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ItalicI
///      fonts:
///       - asset: fonts/italicI.ttf
///
/// 
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
///
import 'package:flutter/widgets.dart';

class CustomIcon {
  CustomIcon._();

  static const _kFontFam = 'ItalicI';
    static const _font = 'icons';

  static const _kFontPkg = null;

  static const IconData info_circled = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info_home = IconData(0xe800, fontFamily:"CircularHome", fontPackage: _kFontPkg);
  static const IconData info_account = IconData(0xe801, fontFamily:"CircularAccount", fontPackage: _kFontPkg);
    static const IconData circle_empty = IconData(0xf10c, fontFamily: "emptyCircle", fontPackage: _kFontPkg);


  static const IconData Mutton = IconData(0xe800, fontFamily: _font, fontPackage: _kFontPkg);
  static const IconData Chicken = IconData(0xea84, fontFamily: _font, fontPackage: _kFontPkg);
  static const IconData SeaFood = IconData(0xea91, fontFamily: _font, fontPackage: _kFontPkg);
  static const IconData Eggs = IconData(0xf7fb, fontFamily: _font, fontPackage: _kFontPkg);

}
